[program:djapi-gunicorn]
command=/home/user/djapi/env/bin/python3 manage.py runserver --bind 0.0.0.0:8000
directory=/home/user/djapi
user=user
numprocs=1
stdout_logfile=/var/log/celery/djapi_gunicorn.log
stderr_logfile=/var/log/celery/djapi_gunicorn.log
autostart=true
autorestart=true
startsecs=10
stopwaitsecs = 600
killasgroup=true
priority=998
